from django.urls import path

from .views import (
  AssemblyMarkingStatusView,
  AssemblyBindMarkingView,
  AssemblyDeleteOrderView,
  AssemblyDeletePickListView,
  AssemblyReprintStickerView,
  AssemblyReplaceOrderView,
  AssemblyScanPrintView,
  AssemblySendAllToAssemblyView,
  AssemblySendToAssemblyView,
  AssemblySendToDeliveryView,
  AssemblySellerDetailView,
  AssemblySellerListView,
  AssemblyPickListPreviewView,
  AssemblyStartView,
  AssemblyVerifyMarkingView,
  OrderListView,
  OrderStatsView,
  OrderSyncView,
  PickListDetailView,
  PickListGenerateView,
  PickListListView,
  SupplyBarcodeView,
  SupplyBulkDeliverView,
  SupplyDeliverView,
  SupplyDetailView,
  SupplyListView,
)
from .views_ozon import (
  OzonAssemblyActView,
  OzonAssemblyBindMarkingView,
  OzonAssemblyLabelView,
  OzonAssemblyScanView,
  OzonAssemblyShipView,
  OzonAssemblySyncView,
)

urlpatterns = [
    path("", OrderListView.as_view(), name="order-list"),
    path("stats/", OrderStatsView.as_view(), name="order-stats"),
    path("sync/", OrderSyncView.as_view(), name="order-sync"),
    path("pick-lists/", PickListListView.as_view(), name="pick-list-list"),
    path("pick-lists/generate/", PickListGenerateView.as_view(), name="pick-list-generate"),
    path("pick-lists/<int:pk>/", PickListDetailView.as_view(), name="pick-list-detail"),
    path("assembly/sellers/", AssemblySellerListView.as_view(), name="assembly-seller-list"),
    path(
      "assembly/sellers/<int:seller_id>/",
      AssemblySellerDetailView.as_view(),
      name="assembly-seller-detail",
    ),
    path(
      "assembly/sellers/<int:seller_id>/start/",
      AssemblyStartView.as_view(),
      name="assembly-start",
    ),
    path(
      "assembly/sellers/<int:seller_id>/pick-list-preview/",
      AssemblyPickListPreviewView.as_view(),
      name="assembly-pick-list-preview",
    ),
    path(
      "assembly/sellers/<int:seller_id>/delete-pick-list/",
      AssemblyDeletePickListView.as_view(),
      name="assembly-delete-pick-list",
    ),
    path(
      "assembly/sellers/<int:seller_id>/delete-order/",
      AssemblyDeleteOrderView.as_view(),
      name="assembly-delete-order",
    ),
    path(
      "assembly/sellers/<int:seller_id>/scan-print/",
      AssemblyScanPrintView.as_view(),
      name="assembly-scan-print",
    ),
    path(
      "assembly/sellers/<int:seller_id>/bind-marking/",
      AssemblyBindMarkingView.as_view(),
      name="assembly-bind-marking",
    ),
    path(
      "assembly/sellers/<int:seller_id>/marking-status/",
      AssemblyMarkingStatusView.as_view(),
      name="assembly-marking-status",
    ),
    path(
      "assembly/sellers/<int:seller_id>/verify-marking/",
      AssemblyVerifyMarkingView.as_view(),
      name="assembly-verify-marking",
    ),
    path(
      "assembly/sellers/<int:seller_id>/replace-order/",
      AssemblyReplaceOrderView.as_view(),
      name="assembly-replace-order",
    ),
    path(
      "assembly/sellers/<int:seller_id>/reprint-sticker/",
      AssemblyReprintStickerView.as_view(),
      name="assembly-reprint-sticker",
    ),
    path(
      "assembly/sellers/<int:seller_id>/send-to-assembly/",
      AssemblySendToAssemblyView.as_view(),
      name="assembly-send-to-assembly",
    ),
    path(
      "assembly/sellers/<int:seller_id>/send-all-to-assembly/",
      AssemblySendAllToAssemblyView.as_view(),
      name="assembly-send-all-to-assembly",
    ),
    path(
      "assembly/sellers/<int:seller_id>/send-to-delivery/",
      AssemblySendToDeliveryView.as_view(),
      name="assembly-send-to-delivery",
    ),
    path(
      "assembly/sellers/<int:seller_id>/ozon-scan/",
      OzonAssemblyScanView.as_view(),
      name="ozon-assembly-scan",
    ),
    path(
      "assembly/sellers/<int:seller_id>/ozon-bind-marking/",
      OzonAssemblyBindMarkingView.as_view(),
      name="ozon-assembly-bind-marking",
    ),
    path(
      "assembly/sellers/<int:seller_id>/ozon-ship/",
      OzonAssemblyShipView.as_view(),
      name="ozon-assembly-ship",
    ),
    path(
      "assembly/sellers/<int:seller_id>/ozon-label/",
      OzonAssemblyLabelView.as_view(),
      name="ozon-assembly-label",
    ),
    path(
      "assembly/sellers/<int:seller_id>/ozon-act/",
      OzonAssemblyActView.as_view(),
      name="ozon-assembly-act",
    ),
    path(
      "assembly/sellers/<int:seller_id>/ozon-sync/",
      OzonAssemblySyncView.as_view(),
      name="ozon-assembly-sync",
    ),
    path("supplies/", SupplyListView.as_view(), name="supply-list"),
    path("supplies/bulk-deliver/", SupplyBulkDeliverView.as_view(), name="supply-bulk-deliver"),
    path("supplies/<int:supply_id>/", SupplyDetailView.as_view(), name="supply-detail"),
    path("supplies/<int:supply_id>/deliver/", SupplyDeliverView.as_view(), name="supply-deliver"),
    path("supplies/<int:supply_id>/barcode/", SupplyBarcodeView.as_view(), name="supply-barcode"),
]
